security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /                
    
    access_control:
       - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: /.*, role: IS_AUTHENTICATED_FULLY }
              
                
    providers:
        user_db:
            entity: { class: Start\StoreBundle\Entity\User, property: username }
    encoders:
        Start\StoreBundle\Entity\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false              